### ISSUE TITLE
Support SSL client certificate authentication

### ISSUE THREAD

**Issue by bluecmd** [GoogleCloudPlatform/nginx-ssl-proxy#5]
Hi,

I would love to see the possibility of having an option to enable SSL client verification.
In nginx this would be:

```
    ssl_client_certificate /etc/secrets/client.crt;
    ssl_verify_client on;
```

I volunteer to write a pull-request for this, if needed and wanted.

**Comment by ChristianUlbrich** [comment]
@bluecmd For the time being, you might be able to "enhance" the config, using my proposed PR #7 enabling additonal config to be passed to nginx.

**Comment by evandbrown** [comment]
Christian's suggestion (which was just merged) seems like it would be a good solution here. Would it work for you, @bluecmd?

**Comment by bluecmd** [comment]
Yea, I think t hat would work. Thanks!
