### ISSUE TITLE
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found

### ISSUE THREAD

**Issue by markshust** [GoogleCloudPlatform/nginx-ssl-proxy#6]
I was receiving this error when testing out the SSL:

```
nginx: [warn] "ssl_stapling" ignored, issuer certificate not found
```

This is because the certificate authority wasn't present for my SSL cert. Adding this line (and appropriate vol mount) fixed it:

`ssl_trusted_certificate /etc/secrets/trusted;`

where /etc/secrets/trusted is the CA.

**Comment by markshust** [comment]
Closing this out -- this was incorrect. I didn't properly bundle the crt file with the CA's. Once you do, this is unneeded.

**Comment by dr-dimitru** [comment]
@markoshust could you please describe how you  _properly bundle crt with CA's_?

**Comment by markshust** [comment]
https://gist.github.com/bradmontgomery/6487319
